In [ ]:
## basic array

In [18]:
arr=np.array([1,2,3])
print(arr)


[1 2 3]


## Basic attributes of nd-array

In [19]:
arr.shape
## ndarray.shape
## returns a tuple consisting of array dimensions

(3,)

In [20]:
arr.ndim
## attribute returns the number of array dimensions.

1

In [21]:
#it returns total no. of elements
arr.size

3

In [22]:
arr1.dtype

dtype('int32')

## Creating nd-array from Python sequences

In [1]:
import numpy as np
#create numpy 1-D array
# Converting Python sequences to NumPy Arrays bcz [1,2,3] is a list
### A list is a data structure in Python that is a mutable, or changeable,
    ordered sequence of elements & it is defined by []
## we can think fofr np.array() or np.asarray()

arr=np.array([1,2,3])
print(arr)


## how to convert a list and tuple into arrays using NumPy.

arr = np.asarray([1,2,3])
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#create numpy multi_D array
arr1=np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [10]:
arr1.shape

(2, 2)

In [11]:
#returns dimensions in array
arr1.ndim

2

In [12]:
#it returns total no. of elements
arr1.size

4

In [13]:
arr1.dtype

dtype('int32')

In [14]:
#we can't create multidimensional-array if dimensions are not same
arr1=np.array([[1,2,3],[4,5]])
arr1

<ipython-input-14-f88dbe543d41>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array([[1,2,3],[4,5]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [17]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

#### how to convert a tuple into numpy arrays 

In [3]:
## how to convert a tuple into numpy arrays 
#### A tuple is a collection which is ordered and unchangeable.
arr = np.asarray((1,2,3))
arr

array([1, 2, 3])

####  how to convert a dict into numpy arrays 

In [4]:
dict1 = {1: 'Geeks',
        2: 'For',
        3: 'Geeks'}

In [6]:
result = dict1.items()
  
# Convert object to a list
data = list(result)


In [7]:
# Convert list to an array
numpyArray = np.array(data)

In [8]:
numpyArray

array([['1', 'Geeks'],
       ['2', 'For'],
       ['3', 'Geeks']], dtype='<U11')

# Indexing in NumPy array

# access element row and col wise

In [ ]:
arr[-2]

In [ ]:
arr[2]

In [13]:
arr1[1:]

array([[3, 4, 0],
       [5, 6, 0]])

In [14]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[:,1:]

array([[2, 0],
       [4, 0],
       [6, 0]])

In [15]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[0:1,1:2]

array([[2]])

In [16]:
arr1[1][2]

0

## Basic Data-types in Numpy :

In [11]:
import numpy as np
a=np.array([1,123,0])

In [12]:
a.dtype

### by-default is int16 , in your system it can be changed  
,it depends upon how your system is complied.. 

dtype('int32')

In [15]:
a=np.array([1,123,0], np.int16)

In [17]:
a.dtype

dtype('int16')

In [13]:
a=np.array([1,123,0], np.int64)

In [14]:
a.dtype

dtype('int64')

In [9]:
a=np.array([1,123,0])
a

array([  1, 123,   0])

In [10]:
a.dtype

dtype('int32')

In [ ]:
dt = np.dtype(float)   # Python-compatible floating-point number
dt = np.dtype(int)     # Python-compatible integer
dt = np.dtype(object)  # Python object

# Arithmetic operations in array

In [ ]:
### Add ,sub ,multiply ,divide(remainder & quotient) ,power(exponent)

In [2]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [24]:
arr+2

## arr + np.array([2,2,2])

array([3, 4, 5])

In [19]:
arr-2

## arr - np.array([2,2,2])

array([-1,  0,  1])

In [20]:
arr*2

## arr * np.array([2,2,2])

array([2, 4, 6])

In [22]:
#exponent 
arr**2

##arr ** np.array([2,2,2])

array([1, 4, 9], dtype=int32)

In [6]:
#returns value ( using division / operator)
arr/2

array([0.5, 1. , 1.5])

In [24]:
#returns remainder ( using modulus % operator)
arr%2

array([1, 0, 1], dtype=int32)

In [5]:
### returns quotient ( using Floor division //)
11//4

2

In [26]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [27]:
b=np.array([7,9,9,4])
b

array([7, 9, 9, 4])

In [28]:
np.add(a,b)# or a+b

array([ 8, 11, 12,  8])

In [29]:
np.multiply(a,b)

array([ 7, 18, 27, 16])

In [30]:
np.power(a,b)

array([    1,   512, 19683,   256], dtype=int32)

In [31]:
np.mod(a,b)

array([1, 2, 3, 0], dtype=int32)

## 4. Statistical functions of numpy ( mean , median , var , std_dev  ,quantile )

In [ ]:
### what is the avg. sale of Laptops ? (Mean)

In [41]:
np.mean([1,4,5,7,7])

4.8

In [ ]:
### what is the middle-value data point in sale of Laptops ?  (Median)

In [43]:
np.median([3,6,8,9,0])

6.0

In [ ]:
### which is the product that gets sold most ??

## use mode over here

In [45]:
from statistics import *

In [46]:
mode(['pc','pc','laptop','pc'])

'pc'

In [ ]:
## variance

In [47]:
np.var([1,4,5,7,7])

4.96

In [ ]:
## Std. dev

In [48]:
np.std([1,4,5,7,7])

2.227105745132009

In [ ]:
## satisfaction score for amazon product for quantiles: 

In [50]:
np.quantile([1,4,5,7,7],0.1)

2.2

## 5..Some basic functions 

#### 1D array- linspace ,arange

In [ ]:
### Lets say I need all values of any ML model parameter ,'no_of estimators' in random_forest as [0,100,200,300]

In [32]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
linspace allows you to define how many values you want by specifying min and max value.

arange allows you to define define how many values you want by specifying min and max value
    (ofcourse this max will be excluded , except in some cases where `step` is not an integer and floating point)
    & the stepsize and returns the total possible values
    

In [35]:
np.arange(1, 1.3, 0.1)


array([1. , 1.1, 1.2, 1.3])

#### 2D array- eye   ( 6 mins )

In [ ]:
As we know Image is all about collection of pixels which can be represented in the form of rows and columns ,

In [ ]:
### use-case
### grey-scale image of '\' ,
### its all about nothing but np.eye(5) bcz where-ever it is 1 ,ie black colour is available
### where-ever it is 0 ,ie white colour is available


In [ ]:
### numpy.eye() create a 2-D array with ones on the diagonal and zeros elsewhere. 

In [39]:
np.eye(5)

## Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### general ndarray creation functions- ones ,zeros  ( 6 mins ) 

In [ ]:
### use-cases -->> https://www.geeksforgeeks.org/digital-image-processing-basics/

In [ ]:
As we know Image is all about collection of pixels which can be represented in the form of rows and columns ,

In [ ]:
Types of an image :

BINARY IMAGE– The binary image as its name suggests, contain only 
               two pixel elements i.e 0 & 1,where 0 refers to black
               and 1 refers to white.

BLACK AND WHITE IMAGE– The image which consist of only black and 
                       white color is called BLACK AND WHITE IMAGE.

8 bit COLOR FORMAT– It is the most famous image format.It has 
                    256 different shades of colors(ie 0-255) in it and 
                   commonly known as Grayscale Image. In this 
                   format, 0 stands for Black, and 255 stands for white, 
                   and 127 stands for gray.

16 bit COLOR FORMAT– It is a color image format. It has 65,536 different
                     colors in it.It is also known as High Color Format.
                     In this format the distribution of color is not as 
                     same as Grayscale image.
                     A 16 bit format is actually divided into three further 
                     formats which are Red, Green and Blue.That famous RGB format. 

In [16]:
### All array elements are initialized to 0, which is created by the zeros() function

np.zeros(5)
## numpy.zeros(shape, [ dtype=None ], [order=’C’])

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
### created array with all the ones..
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### reshaping & flattening of array using reshape ,flatten and ravel

In [21]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a.reshape(6)
## or a.reshape(1,6)

array([1, 2, 3, 4, 5, 6])

In [29]:
a.reshape(3,2)

## deafault order is 'C'
## 'C' means I need in row-major order.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.reshape(3,2,order='F')

## 'F' means I need in column-major 

array([[1, 5],
       [4, 3],
       [2, 6]])

In [14]:
a.flatten(order='C')


# order : {'C', 'F', 'A', 'K'}, optional
#    'C' means to flatten in row-major (C-style) order.
#    'F' means to flatten in column-major 
    
    
    
### returns copy of the array which is collapsed into one dimension.

array([1, 2, 3, 4, 5, 6])

In [15]:


np.ravel(a)

## Return a contiguous flattened array.

array([1, 2, 3, 4, 5, 6])

In [ ]:
### Differences between ravel & flatten

## 6..Conditional functions in numpy (10 mins )
