In [ ]:
## basic array

In [18]:
arr=np.array([1,2,3])
print(arr)


[1 2 3]


## Basic attributes of nd-array

In [19]:
arr.shape
## ndarray.shape
## returns a tuple consisting of array dimensions

(3,)

In [20]:
arr.ndim
## attribute returns the number of array dimensions.

1

In [21]:
#it returns total no. of elements
arr.size

3

In [22]:
arr1.dtype

dtype('int32')

## Creating nd-array from Python sequences

In [1]:
import numpy as np
#create numpy 1-D array
# Converting Python sequences to NumPy Arrays bcz [1,2,3] is a list
### A list is a data structure in Python that is a mutable, or changeable,
    ordered sequence of elements & it is defined by []
## we can think fofr np.array() or np.asarray()

arr=np.array([1,2,3])
print(arr)


## how to convert a list and tuple into arrays using NumPy.

arr = np.asarray([1,2,3])
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#create numpy multi_D array
arr1=np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [10]:
arr1.shape

(2, 2)

In [11]:
#returns dimensions in array
arr1.ndim

2

In [12]:
#it returns total no. of elements
arr1.size

4

In [13]:
arr1.dtype

dtype('int32')

In [14]:
#we can't create multidimensional-array if dimensions are not same
arr1=np.array([[1,2,3],[4,5]])
arr1

<ipython-input-14-f88dbe543d41>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array([[1,2,3],[4,5]])


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [17]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

#### how to convert a tuple into numpy arrays 

In [3]:
## how to convert a tuple into numpy arrays 
#### A tuple is a collection which is ordered and unchangeable.
arr = np.asarray((1,2,3))
arr

array([1, 2, 3])

####  how to convert a dict into numpy arrays 

In [4]:
dict1 = {1: 'Geeks',
        2: 'For',
        3: 'Geeks'}

In [6]:
result = dict1.items()
  
# Convert object to a list
data = list(result)


In [7]:
# Convert list to an array
numpyArray = np.array(data)

In [8]:
numpyArray

array([['1', 'Geeks'],
       ['2', 'For'],
       ['3', 'Geeks']], dtype='<U11')

# Indexing in NumPy array

# access element row and col wise

In [ ]:
arr[-2]

In [ ]:
arr[2]

In [13]:
arr1[1:]

array([[3, 4, 0],
       [5, 6, 0]])

In [14]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[:,1:]

array([[2, 0],
       [4, 0],
       [6, 0]])

In [15]:
arr1=np.array([[1,2,0],[3,4,0],[5,6,0]])
arr1[0:1,1:2]

array([[2]])

In [16]:
arr1[1][2]

0

## Basic Data-types in Numpy :

In [11]:
import numpy as np
a=np.array([1,123,0])

In [12]:
a.dtype

### by-default is int16 , in your system it can be changed  
,it depends upon how your system is complied.. 

dtype('int32')

In [15]:
a=np.array([1,123,0], np.int16)

In [17]:
a.dtype

dtype('int16')

In [13]:
a=np.array([1,123,0], np.int64)

In [14]:
a.dtype

dtype('int64')

In [9]:
a=np.array([1,123,0])
a

array([  1, 123,   0])

In [10]:
a.dtype

dtype('int32')

In [ ]:
dt = np.dtype(float)   # Python-compatible floating-point number
dt = np.dtype(int)     # Python-compatible integer
dt = np.dtype(object)  # Python object

# Arithmetic operations in array

In [23]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [24]:
arr+2

## arr + np.array([2,2,2])

array([3, 4, 5])

In [19]:
arr-2

## arr - np.array([2,2,2])

array([-1,  0,  1])

In [20]:
arr*2

## arr * np.array([2,2,2])

array([2, 4, 6])

In [22]:
#exponent 
arr**2

##arr ** np.array([2,2,2])

array([1, 4, 9], dtype=int32)

In [24]:
#returns remainder
arr%2

array([1, 0, 1], dtype=int32)

In [25]:
#returns quotient
arr/2

array([0.5, 1. , 1.5])

In [26]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [27]:
b=np.array([7,9,9,4])
b

array([7, 9, 9, 4])

In [28]:
np.add(a,b)# or a+b

array([ 8, 11, 12,  8])

In [29]:
np.multiply(a,b)

array([ 7, 18, 27, 16])

In [30]:
np.power(a,b)

array([    1,   512, 19683,   256], dtype=int32)

In [31]:
np.mod(a,b)

array([1, 2, 3, 0], dtype=int32)