<h2> 3.6 Featurizing text data with tfidf weighted word-vectors </h2>

In [ ]:
### when we peeform wordcloud analysis , then we have analysed that there is a some value of some of the words
### as they repeate more often in class 0 & class 1 wordcloud.. like Donald trimph etc..



In [2]:
#!pip install spacy

  Using cached https://files.pythonhosted.org/packages/55/9c/509647aecd01679474ef3646b68b3b3a909bdfa3e09ec12a85344b1d2948/spacy-3.0.5-cp37-cp37m-win_amd64.whl


In [ ]:
## so lets use tfidf weighted word-vectors to featurize text data


In [72]:
#!pip install nltk


In [ ]:
#### Storing data into database

In [ ]:
## then we are dumping the total data in sqlite database as sqlite is a most popular & simplest databases in q world 
## that u can see on your andriod phones , iphones  , most of the MacBooks  , 
## so in Android or Iphones when u store your contact number , they will get stored in SQLiite
## In python , we have q in-built module to interact with SQLIte

In [2]:
import pandas as pd
data=pd.read_csv(r'F:\Learn_ai_ml_da\Quora\5.Adv_fe\nlp_features_train.csv')

In [3]:
data.head(2)

Unnamed: 0  id  qid1  qid2  \
0           0   0     1     2   
1           1   1     3     4   

                                           question1  \
0  what is the step by step guide to invest in sh...   
1  what is the story of kohinoor  koh i noor  dia...   

                                           question2  is_duplicate  freq_qid1  \
0  what is the step by step guide to invest in sh...             0          1   
1  what would happen if the indian government sto...             0          4   

   freq_qid2  q1len  ...  last_word  first_word  length_diff   cwc_min  \
0          1     66  ...          0           1            2  0.833333   
1          1     51  ...          0           1            5  0.714286   

    cwc_max  csc_min   csc_max   ctc_min   ctc_max  mean_length  
0  0.714286      1.0  0.857143  0.416667  0.357143         13.0  
1  0.416667      0.6  0.600000  0.416667  0.294118         14.5  

[2 rows x 33 columns]

In [4]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
data.columns

Index(['id', 'qid1', 'qid2', 'question1', 'question2', 'is_duplicate',
       'freq_qid1', 'freq_qid2', 'q1len', 'q2len', 'q1_n_words', 'q2_n_words',
       'word_common', 'word_Total', 'word_share', 'freq_q1+q2', 'freq_q1-q2',
       'fuzz_ratio', 'fuzz_partial_ratio', 'Token_Sort_Ratio',
       'Token_Set_Ratio', 'Longest_substr_ratio', 'last_word', 'first_word',
       'length_diff', 'cwc_min', 'cwc_max', 'csc_min', 'csc_max', 'ctc_min',
       'ctc_max', 'mean_length'],
      dtype='object')

In [6]:
data.shape

(10000, 32)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import time
import warnings
import numpy as np
from nltk.corpus import stopwords
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
import pandas as pd
data=pd.read_csv(r'F:\Learn_ai_ml_da\Quora\5.Adv_fe/nlp_features_train.csv')


In [4]:
data.columns

Index(['Unnamed: 0', 'id', 'qid1', 'qid2', 'question1', 'question2',
       'is_duplicate', 'freq_qid1', 'freq_qid2', 'q1len', 'q2len',
       'q1_n_words', 'q2_n_words', 'word_common', 'word_Total', 'word_share',
       'freq_q1+q2', 'freq_q1-q2', 'fuzz_ratio', 'fuzz_partial_ratio',
       'Token_Sort_Ratio', 'Token_Set_Ratio', 'Longest_substr_ratio',
       'last_word', 'first_word', 'length_diff', 'cwc_min', 'cwc_max',
       'csc_min', 'csc_max', 'ctc_min', 'ctc_max', 'mean_length'],
      dtype='object')

In [5]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [6]:
data.head(2)

id  qid1  qid2                                          question1  \
0   0     1     2  what is the step by step guide to invest in sh...   
1   1     3     4  what is the story of kohinoor  koh i noor  dia...   

                                           question2  is_duplicate  freq_qid1  \
0  what is the step by step guide to invest in sh...             0          1   
1  what would happen if the indian government sto...             0          4   

   freq_qid2  q1len  q2len  ...  last_word  first_word  length_diff   cwc_min  \
0          1     66     57  ...          0           1            2  0.833333   
1          1     51     88  ...          0           1            5  0.714286   

    cwc_max  csc_min   csc_max   ctc_min   ctc_max  mean_length  
0  0.714286      1.0  0.857143  0.416667  0.357143         13.0  
1  0.416667      0.6  0.600000  0.416667  0.294118         14.5  

[2 rows x 32 columns]

In [8]:
## now we have to convert this question 1 & question 2 into vectors

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
tfidf = TfidfVectorizer(lowercase=False)

In [9]:
matrix=tfidf.fit_transform(data['question1'])

In [10]:
matrix

<10000x11733 sparse matrix of type '<class 'numpy.float64'>'
	with 100364 stored elements in Compressed Sparse Row format>

In [11]:
### Tfidf representation of data..
matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
## Get Features names


In [12]:
len(tfidf.get_feature_names()) 
### ie 10K data points are represented using 11733 cols..

11733

In [ ]:
#tfidf.get_feature_names()

In [14]:
tfidf.idf_
### tf-idf score of each feature can be retrieved via the attribute idf_ of the TfidfVectorizer object:

array([9.51729319, 9.51729319, 9.11182808, ..., 9.51729319, 9.51729319,
       9.51729319])

In [15]:
len(tfidf.idf_)

11733

In [16]:
word2tfidf = dict(zip(tfidf.get_feature_names(), tfidf.idf_))

In [ ]:
word2tfidf

In [18]:
word2tfidf['anthem']

8.130998825296679

In [19]:
data['question1'][0]

'what is the step by step guide to invest in share market in india'

In [21]:

### finding TF_IDF scores of each word of data['question1'][0]

for word1 in data['question1'][0].split(' '):
    idf = word2tfidf[str(word1)]
    print('{}: {}'.format(word1 , idf))

what: 1.9345546975021595
is: 2.1108860846001516
the: 1.96636909668073
step: 8.130998825296679
by: 4.8923203731323
step: 8.130998825296679
guide: 8.824146005856626
to: 2.540478371502939
invest: 7.571383037361257
in: 2.5092401861190696
share: 7.3200686090803515
market: 7.074946151047366
in: 2.5092401861190696
india: 4.426615184646779


In [ ]:
'''
NLTK provides access to many algorithms to get something done, 
spaCy provides the best way to do it. It provides the fastest and most accurate syntactic analysis
of any NLP library . It also offers access to larger word vectors that are easier to customize.

'''

In [26]:
#!pip install spacy

In [27]:
import spacy

In [28]:
spacy.__version__

'3.2.1'

In [29]:
#!python -m spacy download en_core_web_sm

[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [23]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [24]:
nlp
# en_vectors_web_lg, which includes over 1 million unique vectors.



In [91]:
### lets understand vector representation of "apple cat sky" using word2vec..
tokens = nlp("apple cat sky")

In [92]:
print(tokens.text)

apple cat sky


In [96]:
print(tokens.vector)

[ 0.40506864  0.22128649  0.19954528 -0.18354528  0.28327683  0.07169196
 -0.34436452 -0.34994462 -0.31051207  1.0672301   0.06619611 -0.5366481
  0.84517735  0.2672817  -0.22981946  1.0821568  -0.31566915  0.7936122
  0.31160533  1.1357889  -0.29438975 -0.89795876  0.19286746 -0.6470776
  0.53080046  0.24411018 -1.1490146  -0.32978198  0.6831515  -0.5308773
  1.0964357  -1.0723451   0.20477664 -0.35069188  0.8525457  -1.0272217
 -0.3377669  -0.22337551 -0.46683168  1.5822481  -0.85350275  0.18484996
  0.44748282  0.39866793 -0.25303558  0.22335869 -0.04402099 -0.58198184
  1.3364382  -0.2035625   0.20985688  0.16480033  0.06581709 -0.78883654
 -0.06355637  0.8298394  -0.60205334  0.47620955  0.11180221 -0.0922114
 -0.91972476 -0.19026308 -0.2816516  -0.6168538  -0.2613859   0.22310746
 -0.20091581 -0.52342194  0.2718579  -1.1318685   0.2819316  -0.22226393
 -0.26446682 -0.05982925 -0.00500856 -0.32686886 -0.3745903   0.04326912
  0.48165783 -0.44403794  0.7546126  -0.21893688  0.07923

In [31]:
data['question1'][0]

'what is the step by step guide to invest in share market in india'

In [32]:
data['question2'][0]

'what is the step by step guide to invest in share market'

In [33]:
len(data['question1'][0])

65

In [34]:
# pip install tqdm
from tqdm import tqdm

### tqdm is a library in Python which is used for creating Progress Meters or Progress Bars.

In [36]:
tqdm(data['question1'][0])

## tqdm(iterable)---just to show a smart progress meter - 
# just wrap any iterable with tqdm(iterable), and you're done!

# returning an iterator which acts exactly like the original iterable, but prints a dynamically updating
# progress bar every time a value is requested


  0%|                                                                                           | 0/65 [00:00<?, ?it/s]

In [ ]:
#### lets find vector representation of data['question1'][0] using spacy...

In [25]:
doc1 = nlp(data['question1'][1])

In [26]:
type(doc1)

### tokens-->> An individual token — i.e. a word, punctuation symbol, whitespace, etc

spacy.tokens.doc.Doc

In [27]:
## to access vector of doc1

doc1.vector

array([ 0.27182725, -0.22748564, -0.40640107,  0.13880645,  0.05647859,
        0.14738564, -0.58092886,  0.0369109 ,  0.11776315, -0.10288119,
       -0.4712915 , -0.39010152,  0.01995653,  0.2506573 ,  0.28495976,
        0.43747166,  0.15864624,  0.2383338 ,  0.32579163, -0.2672591 ,
       -0.41166082, -0.3874631 ,  0.3795617 ,  0.25720546, -0.46166667,
       -0.24692422, -0.18953204, -0.33242467,  0.06336411, -0.35838854,
        0.27248672, -1.0098429 ,  0.47178856, -0.29100433,  0.19183826,
       -0.57845014,  0.23445748,  0.78777534, -0.07061777, -0.10548332,
       -0.17790681, -0.45317402,  0.37463936,  0.25170687,  0.16364752,
        0.3196623 ,  0.24477272,  0.16747598,  0.49165788,  0.03842891,
       -0.05180456,  0.41792166, -0.08040768, -0.30392668,  0.10952846,
       -0.07997428, -0.02804138,  0.14800772,  0.24343048, -0.29215083,
        0.28092813, -0.03025008, -0.32573673, -0.20013694,  0.09704671,
       -0.38019654,  0.3125867 ,  0.01518611, -0.10593425, -0.63

In [28]:
len(doc1.vector)

96

In [29]:
len(doc1)

12

In [30]:
import numpy as np
np.zeros([len(doc1), len(doc1[0].vector)])

## ie 12*96 dimensions

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
np.zeros([len(doc1), len(doc1[0].vector)]).shape

(12, 96)

In [34]:
mean_vec=np.zeros([len(doc1), len(doc1[0].vector)])

In [35]:
mean_vec

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
type(word2tfidf)

dict

In [115]:
data['question1'][1]

'what is the story of kohinoor  koh i noor  diamond'

In [132]:
doc1 = nlp(data['question1'][1])

In [133]:
len(doc1)

12

In [118]:
### vector representation of entire document..
doc1.vector

array([ 0.27182725, -0.22748564, -0.40640107,  0.13880645,  0.05647859,
        0.14738564, -0.58092886,  0.0369109 ,  0.11776315, -0.10288119,
       -0.4712915 , -0.39010152,  0.01995653,  0.2506573 ,  0.28495976,
        0.43747166,  0.15864624,  0.2383338 ,  0.32579163, -0.2672591 ,
       -0.41166082, -0.3874631 ,  0.3795617 ,  0.25720546, -0.46166667,
       -0.24692422, -0.18953204, -0.33242467,  0.06336411, -0.35838854,
        0.27248672, -1.0098429 ,  0.47178856, -0.29100433,  0.19183826,
       -0.57845014,  0.23445748,  0.78777534, -0.07061777, -0.10548332,
       -0.17790681, -0.45317402,  0.37463936,  0.25170687,  0.16364752,
        0.3196623 ,  0.24477272,  0.16747598,  0.49165788,  0.03842891,
       -0.05180456,  0.41792166, -0.08040768, -0.30392668,  0.10952846,
       -0.07997428, -0.02804138,  0.14800772,  0.24343048, -0.29215083,
        0.28092813, -0.03025008, -0.32573673, -0.20013694,  0.09704671,
       -0.38019654,  0.3125867 ,  0.01518611, -0.10593425, -0.63

In [ ]:
### word-2vec representation of our doc1..
for word in doc1:
    print('{}:{}'.format(word,word.vector))
    print('\n')

In [60]:
### getting tf-idf scores of each of 'what is the story of kohinoor  koh i noor  diamond'

for word1 in doc1:
    try:
        idf = word2tfidf[str(word1)]
    except:
        idf = 0
    print('{}: {}'.format(word1 , idf))

what: 1.9345546975021595
is: 2.1108860846001516
the: 1.96636909668073
step: 8.130998825296679
by: 4.8923203731323
step: 8.130998825296679
guide: 8.824146005856626
to: 2.540478371502939
invest: 7.571383037361257
in: 2.5092401861190696
share: 7.3200686090803515
market: 7.074946151047366
in: 2.5092401861190696
india: 4.426615184646779


In [61]:
doc1=nlp(data['question1'][0])
mean_vec=np.zeros([len(doc1), len(doc1[0].vector)])

In [62]:
for word1 in doc1:
    ##word2vec
    vec1 = word1.vector
    
    # fetch idf score
    try:
        idf = word2tfidf[str(word1)]
    except:
        idf = 0
            # compute final vec
    mean_vec =mean_vec +  vec1 * idf



In [63]:
mean_vec

array([[23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243],
       [23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243],
       [23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243],
       ...,
       [23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243],
       [23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243],
       [23.90720253, 40.47232097, 37.90055621, ..., 36.8611511 ,
         2.36926514, 11.32498243]])

In [64]:
mean_vec[0][0]

23.907202528323978

In [65]:
mean_vec[1][0]

23.907202528323978

In [66]:
mean_vec[2][0]

23.907202528323978

In [67]:
print(mean_vec.mean(axis=0))    

### axis = 0 means along the column 

[ 23.90720253  40.47232097  37.90055621   4.52990833  35.50312129
  -9.02008093  -6.61869168 -11.121927     5.91599393   5.05029839
 -24.87516662 -18.77832818  41.91717255  -8.78664294   6.91323152
  31.26427984 -14.01699027   1.57351182  -1.05047505  30.96636674
 -15.13095724 -22.69204438  -1.63542178  23.77699713   8.49037634
   4.73834682 -48.82118258 -49.92386091  -1.48075118 -22.20794654
  43.95905375  -7.61658013  17.98550228 -24.51892704  45.1947799
 -38.32733732   2.05920514 -22.3042853   -7.62715605  22.25790955
 -17.7439025  -38.84025335   3.91442817   8.908587   -37.29320449
  -7.00171676 -34.02818117 -38.78419039  64.13125295 -13.82171585
 -16.32293326   0.64774304 -21.61813757   1.2829338    5.0602572
 -21.99188492 -36.44814632   9.04360445   2.11300939 -20.50683078
   8.98547632 -39.27402663  13.07975029 -15.59581403 -13.05298924
  -2.25980686  -6.06121053 -27.77708037   1.67761663 -36.67946675
 -13.55795521 -24.75473743 -15.64016837  16.24039148  10.32045356
   7.7907032

### lets apply TF_IDF weighted Word-2-vec on 'question1' feature..

In [45]:
from tqdm import tqdm
vecs1 = []
# https://github.com/noamraph/tqdm
# tqdm is used to print the progress bar
for qu1 in tqdm(list(data['question1'])):
    doc1 = nlp(qu1) 
    # 384 is the number of dimensions of vectors 
    mean_vec1 = np.zeros([len(doc1), len(doc1[0].vector)])
    for word1 in doc1:
        # word2vec
        vec1 = word1.vector
        # fetch tf-idf score score
        try:
            idf = word2tfidf[str(word1)]
        except:
            idf = 0
        # compute final vec
        mean_vec1 += vec1 * idf
    mean_vec1 = mean_vec1.mean(axis=0)
    vecs1.append(mean_vec1)


100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [03:06<00:00, 53.66it/s]


In [ ]:
##vecs1

In [46]:
### TF_IDF weighted Word-2-vec on data['question1'][0]
vecs1[0]

array([ 23.90720253,  40.47232097,  37.90055621,   4.52990833,
        35.50312129,  -9.02008093,  -6.61869168, -11.121927  ,
         5.91599393,   5.05029839, -24.87516662, -18.77832818,
        41.91717255,  -8.78664294,   6.91323152,  31.26427984,
       -14.01699027,   1.57351182,  -1.05047505,  30.96636674,
       -15.13095724, -22.69204438,  -1.63542178,  23.77699713,
         8.49037634,   4.73834682, -48.82118258, -49.92386091,
        -1.48075118, -22.20794654,  43.95905375,  -7.61658013,
        17.98550228, -24.51892704,  45.1947799 , -38.32733732,
         2.05920514, -22.3042853 ,  -7.62715605,  22.25790955,
       -17.7439025 , -38.84025335,   3.91442817,   8.908587  ,
       -37.29320449,  -7.00171676, -34.02818117, -38.78419039,
        64.13125295, -13.82171585, -16.32293326,   0.64774304,
       -21.61813757,   1.2829338 ,   5.0602572 , -21.99188492,
       -36.44814632,   9.04360445,   2.11300939, -20.50683078,
         8.98547632, -39.27402663,  13.07975029, -15.59

In [68]:
len(vecs1)

10000

In [69]:
from tqdm import tqdm
vecs2 = []
# https://github.com/noamraph/tqdm
# tqdm is used to print the progress bar
for qu2 in tqdm(list(data['question2'])):
    doc2 = nlp(qu2) 
    # 384 is the number of dimensions of vectors 
    mean_vec2 = np.zeros([len(doc2), len(doc2[0].vector)])
    for word2 in doc2:
        # word2vec
        vec2 = word2.vector
        # fetch tf-idf score score
        try:
            idf = word2tfidf[str(word2)]
        except:
            idf = 0
        # compute final vec
        mean_vec2 += vec2 * idf
    mean_vec2 = mean_vec2.mean(axis=0)
    vecs2.append(mean_vec2)


100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [02:30<00:00, 66.40it/s]


In [70]:
df=pd.DataFrame()

In [75]:
## now we have vectors , we have to insert it into dataframe
df['q1_feats_m'] = vecs1
df['q2_feats_m'] = vecs2

In [76]:
df.shape

(10000, 2)

In [77]:
df.head()

q1_feats_m  \
0  [23.907202528323978, 40.47232096642256, 37.900...   
1  [-0.9288597628474236, -5.198762834072113, -13....   
2  [4.859346032142639, 18.802284240722656, 26.502...   
3  [-18.424417197704315, 12.57970809750259, -7.22...   
4  [60.89346182346344, 51.92742878198624, -2.3153...   

                                          q2_feats_m  
0  [17.477654264774173, 32.19557575881481, 45.410...  
1  [9.14291419647634, 4.996194444131106, 11.57384...  
2  [14.711802423000336, 17.87611384689808, 14.453...  
3  [-12.734007477760315, 3.7158855088055134, -12....  
4  [10.928872123360634, 29.19583797454834, 30.534...

In [74]:
df['q1_feats_m'][0]

### representation of data['question1'][0]
### ie ,''what is the step by step guide to invest in share market in india''

array([ 23.90720253,  40.47232097,  37.90055621,   4.52990833,
        35.50312129,  -9.02008093,  -6.61869168, -11.121927  ,
         5.91599393,   5.05029839, -24.87516662, -18.77832818,
        41.91717255,  -8.78664294,   6.91323152,  31.26427984,
       -14.01699027,   1.57351182,  -1.05047505,  30.96636674,
       -15.13095724, -22.69204438,  -1.63542178,  23.77699713,
         8.49037634,   4.73834682, -48.82118258, -49.92386091,
        -1.48075118, -22.20794654,  43.95905375,  -7.61658013,
        17.98550228, -24.51892704,  45.1947799 , -38.32733732,
         2.05920514, -22.3042853 ,  -7.62715605,  22.25790955,
       -17.7439025 , -38.84025335,   3.91442817,   8.908587  ,
       -37.29320449,  -7.00171676, -34.02818117, -38.78419039,
        64.13125295, -13.82171585, -16.32293326,   0.64774304,
       -21.61813757,   1.2829338 ,   5.0602572 , -21.99188492,
       -36.44814632,   9.04360445,   2.11300939, -20.50683078,
         8.98547632, -39.27402663,  13.07975029, -15.59

In [78]:
df_q1=pd.DataFrame(df['q1_feats_m'].values.tolist())
df_q1

0          1          2          3          4          5   \
0     23.907203  40.472321  37.900556   4.529908  35.503121  -9.020081   
1     -0.928860  -5.198763 -13.121864  17.536415   0.188638  -5.088941   
2      4.859346  18.802284  26.502613  24.812698  15.628155  -7.269202   
3    -18.424417  12.579708  -7.223645  -6.140553  -5.770353   8.072301   
4     60.893462  51.927429  -2.315364  27.468217  -1.479878 -17.789400   
...         ...        ...        ...        ...        ...        ...   
9995  32.366060  80.957453  -3.934128  12.798635 -54.040079 -40.197860   
9996   5.997746  -3.655029   3.621464  13.943520   0.959427   0.689709   
9997 -21.091403  13.565457  -8.987760  48.199340   4.639438 -45.031122   
9998  18.283654   1.414458   3.152174  -8.975198   8.804844  -4.287237   
9999  -1.641423  59.344096 -21.979493   5.587328  22.652188  -9.082759   

             6          7          8          9   ...         86         87  \
0     -6.618692 -11.121927   5.915994   5.050298  ...  26.421438 -24.469537   
1    -42.789579  -6.518492   7.445017  -5.099011  ...  21.727246 -12.732510   
2    -23.030877 -13.509516  -5.467509  23.472172  ...  -2.361464  -9.131316   
3    -31.995034   0.738632  -6.695852  -5.642807  ... -17.033904 -20.732621   
4    -52.976324  32.048990  -0.158303  -4.990396  ...  28.309581 -46.541785   
...         ...        ...        ...        ...  ...        ...        ...   
9995 -86.170029  25.179359   9.124863 -26.593170  ...  48.794786 -55.686242   
9996  -7.791149  -0.848879  -3.385175  16.258465  ...   0.650375 -23.420215   
9997 -42.282054  14.797562 -19.470021   5.471248  ...   6.470193  -8.399501   
9998 -17.739329  -6.467739  -9.042717 -16.046217  ...  19.636550 -23.143692   
9999 -41.626342  16.561204 -21.228494  13.685563  ... -20.822675 -43.473232   

             88         89         90         91         92         93  \
0    -22.466004  18.608622 -17.145382  23.524949  26.463098  36.861151   
1    -11.914686  19.629429 -17.504095   1.549989  14.447148   1.306046   
2    -12.991115  28.734291 -30.128246  21.449709   0.834497   6.398972   
3    -10.156215   0.351461   0.195305  13.990964  -0.505837  14.271471   
4     -3.386737  -4.731353 -68.532564 -10.852401  23.794325  48.257632   
...         ...        ...        ...        ...        ...        ...   
9995  52.992770  -2.590952 -50.204407 -45.171588  83.847828  83.308107   
9996  -5.704029 -22.953041  -5.380829  -4.560248 -10.590099   6.433664   
9997  -0.510728  -9.487310  21.290559  24.460720  32.152824  31.114698   
9998 -14.209467  -4.013208  -9.701900  11.317953 -12.912168  26.448947   
9999   8.192125  30.881819  37.354073  46.427026  24.696542  26.604150   

             94         95  
0      2.369265  11.324982  
1     17.799027  11.975020  
2     26.110739 -20.355668  
3     53.701465  -3.207658  
4    -15.891580  -2.547915  
...         ...        ...  
9995 -21.596561 -34.763464  
9996  12.145354  -0.750654  
9997 -24.704132 -15.066327  
9998  -1.271957  27.129842  
9999  -7.607696 -14.710141  

[10000 rows x 96 columns]

In [56]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [79]:
df_q1=pd.DataFrame(df['q1_feats_m'].values.tolist(),\
                   index=df.index)

In [80]:

df_q2=pd.DataFrame(df['q2_feats_m'].values.tolist(),\
                   index= df.index)

In [81]:
# Questions 1 tfidf weighted word2vec
df_q1.head()

0          1          2          3          4          5   \
0  23.907203  40.472321  37.900556   4.529908  35.503121  -9.020081   
1  -0.928860  -5.198763 -13.121864  17.536415   0.188638  -5.088941   
2   4.859346  18.802284  26.502613  24.812698  15.628155  -7.269202   
3 -18.424417  12.579708  -7.223645  -6.140553  -5.770353   8.072301   
4  60.893462  51.927429  -2.315364  27.468217  -1.479878 -17.789400   

          6          7         8          9   ...         86         87  \
0  -6.618692 -11.121927  5.915994   5.050298  ...  26.421438 -24.469537   
1 -42.789579  -6.518492  7.445017  -5.099011  ...  21.727246 -12.732510   
2 -23.030877 -13.509516 -5.467509  23.472172  ...  -2.361464  -9.131316   
3 -31.995034   0.738632 -6.695852  -5.642807  ... -17.033904 -20.732621   
4 -52.976324  32.048990 -0.158303  -4.990396  ...  28.309581 -46.541785   

          88         89         90         91         92         93  \
0 -22.466004  18.608622 -17.145382  23.524949  26.463098  36.861151   
1 -11.914686  19.629429 -17.504095   1.549989  14.447148   1.306046   
2 -12.991115  28.734291 -30.128246  21.449709   0.834497   6.398972   
3 -10.156215   0.351461   0.195305  13.990964  -0.505837  14.271471   
4  -3.386737  -4.731353 -68.532564 -10.852401  23.794325  48.257632   

          94         95  
0   2.369265  11.324982  
1  17.799027  11.975020  
2  26.110739 -20.355668  
3  53.701465  -3.207658  
4 -15.891580  -2.547915  

[5 rows x 96 columns]

In [82]:
# Questions 2 tfidf weighted word2vec
df_q2.head()

0          1          2          3          4          5   \
0  17.477654  32.195576  45.410675  11.977170  32.140069  -4.348896   
1   9.142914   4.996194  11.573846  31.183774   6.463360  -2.656363   
2  14.711802  17.876114  14.453310   3.960203  14.996328   6.442080   
3 -12.734007   3.715886 -12.751522  60.119850   3.343229 -43.417467   
4  10.928872  29.195838  30.534088  -1.782759  17.398814   4.186934   

          6          7          8          9   ...         86         87  \
0  -2.945671 -14.010186   1.839392   6.219155  ...  21.223358 -21.935678   
1 -37.870281   4.299118   4.216336   0.887311  ...  30.260581 -16.300661   
2 -26.328218   9.858288   0.577384 -14.460326  ...   2.711055 -29.881010   
3 -57.588195  -1.811320 -16.830395  10.821902  ...   8.634554   7.008690   
4 -17.112002   6.677448   9.702506  10.918537  ...  24.293332 -16.404147   

          88         89         90         91         92         93  \
0 -22.791324  15.962263 -19.233140  16.063902  28.513158  43.788944   
1 -13.374940  44.581193 -37.854236   7.180397  18.755975  10.925541   
2 -22.673592  46.088642 -17.108936   2.803065   9.532278  10.161055   
3  27.216871 -24.295948 -33.744450  -6.410545  26.177300  35.995368   
4  -5.434019  16.523209 -37.312551   4.727493  19.779195  20.040438   

          94         95  
0   5.022592   1.412331  
1  10.160813  11.768808  
2  18.527590   0.603332  
3  11.100443 -11.795188  
4  12.406490 -14.644234  

[5 rows x 96 columns]

In [83]:
data.head(2)

id  qid1  qid2                                          question1  \
0   0     1     2  what is the step by step guide to invest in sh...   
1   1     3     4  what is the story of kohinoor  koh i noor  dia...   

                                           question2  is_duplicate  freq_qid1  \
0  what is the step by step guide to invest in sh...             0          1   
1  what would happen if the indian government sto...             0          4   

   freq_qid2  q1len  q2len  ...  last_word  first_word  length_diff   cwc_min  \
0          1     66     57  ...          0           1            2  0.833333   
1          1     51     88  ...          0           1            5  0.714286   

    cwc_max  csc_min   csc_max   ctc_min   ctc_max  mean_length  
0  0.714286      1.0  0.857143  0.416667  0.357143         13.0  
1  0.416667      0.6  0.600000  0.416667  0.294118         14.5  

[2 rows x 32 columns]

In [84]:
dfnlp = data.drop(['qid1','qid2','question1','question2'],\
                  axis=1)

In [85]:
dfnlp.head(2)

id  is_duplicate  freq_qid1  freq_qid2  q1len  q2len  q1_n_words  \
0   0             0          1          1     66     57          14   
1   1             0          4          1     51     88           8   

   q2_n_words  word_common  word_Total  ...  last_word  first_word  \
0          12           10          23  ...          0           1   
1          13            4          20  ...          0           1   

   length_diff   cwc_min   cwc_max  csc_min   csc_max   ctc_min   ctc_max  \
0            2  0.833333  0.714286      1.0  0.857143  0.416667  0.357143   
1            5  0.714286  0.416667      0.6  0.600000  0.416667  0.294118   

   mean_length  
0         13.0  
1         14.5  

[2 rows x 28 columns]

In [86]:
dfnlp.shape

(10000, 28)

In [ ]:
### now we have to merge df_q1 & df_q2 on the basis of id column

In [87]:
df_q1['id']=dfnlp['id']
df_q2['id']=dfnlp['id']


In [88]:
df_q1.shape

(10000, 97)

In [89]:
df3=df_q1.merge(df_q2, on='id',how='left')

In [90]:
df3.head()

0_x        1_x        2_x        3_x        4_x        5_x  \
0  23.907203  40.472321  37.900556   4.529908  35.503121  -9.020081   
1  -0.928860  -5.198763 -13.121864  17.536415   0.188638  -5.088941   
2   4.859346  18.802284  26.502613  24.812698  15.628155  -7.269202   
3 -18.424417  12.579708  -7.223645  -6.140553  -5.770353   8.072301   
4  60.893462  51.927429  -2.315364  27.468217  -1.479878 -17.789400   

         6_x        7_x       8_x        9_x  ...       86_y       87_y  \
0  -6.618692 -11.121927  5.915994   5.050298  ...  21.223358 -21.935678   
1 -42.789579  -6.518492  7.445017  -5.099011  ...  30.260581 -16.300661   
2 -23.030877 -13.509516 -5.467509  23.472172  ...   2.711055 -29.881010   
3 -31.995034   0.738632 -6.695852  -5.642807  ...   8.634554   7.008690   
4 -52.976324  32.048990 -0.158303  -4.990396  ...  24.293332 -16.404147   

        88_y       89_y       90_y       91_y       92_y       93_y  \
0 -22.791324  15.962263 -19.233140  16.063902  28.513158  43.788944   
1 -13.374940  44.581193 -37.854236   7.180397  18.755975  10.925541   
2 -22.673592  46.088642 -17.108936   2.803065   9.532278  10.161055   
3  27.216871 -24.295948 -33.744450  -6.410545  26.177300  35.995368   
4  -5.434019  16.523209 -37.312551   4.727493  19.779195  20.040438   

        94_y       95_y  
0   5.022592   1.412331  
1  10.160813  11.768808  
2  18.527590   0.603332  
3  11.100443 -11.795188  
4  12.406490 -14.644234  

[5 rows x 193 columns]

In [ ]:
## as dfnlp.shape has 28 columns including id 
## & vectors df3 has 193 columns (96 each & including ID)


## so Total must be 193+28-1=220 columns 

In [92]:
print(df3.shape[1],dfnlp.shape[1])

193 28


In [93]:
df4=df3.merge(dfnlp, on='id',how='left')

In [94]:
df4.head()

0_x        1_x        2_x        3_x        4_x        5_x  \
0  23.907203  40.472321  37.900556   4.529908  35.503121  -9.020081   
1  -0.928860  -5.198763 -13.121864  17.536415   0.188638  -5.088941   
2   4.859346  18.802284  26.502613  24.812698  15.628155  -7.269202   
3 -18.424417  12.579708  -7.223645  -6.140553  -5.770353   8.072301   
4  60.893462  51.927429  -2.315364  27.468217  -1.479878 -17.789400   

         6_x        7_x       8_x        9_x  ...  last_word  first_word  \
0  -6.618692 -11.121927  5.915994   5.050298  ...          0           1   
1 -42.789579  -6.518492  7.445017  -5.099011  ...          0           1   
2 -23.030877 -13.509516 -5.467509  23.472172  ...          0           1   
3 -31.995034   0.738632 -6.695852  -5.642807  ...          0           0   
4 -52.976324  32.048990 -0.158303  -4.990396  ...          0           1   

   length_diff   cwc_min   cwc_max  csc_min   csc_max   ctc_min   ctc_max  \
0            2  0.833333  0.714286      1.0  0.857143  0.416667  0.357143   
1            5  0.714286  0.416667      0.6  0.600000  0.416667  0.294118   
2            4  0.400000  0.333333      0.4  0.250000  0.200000  0.142857   
3            6  0.250000  0.071429      0.0  0.000000  0.083333  0.055556   
4            8  0.400000  0.166667      1.0  0.666667  0.285714  0.133333   

   mean_length  
0         13.0  
1         14.5  
2         12.0  
3         15.0  
4         11.0  

[5 rows x 220 columns]

In [95]:
df4.columns[-28:]

Index(['95_y', 'is_duplicate', 'freq_qid1', 'freq_qid2', 'q1len', 'q2len',
       'q1_n_words', 'q2_n_words', 'word_common', 'word_Total', 'word_share',
       'freq_q1+q2', 'freq_q1-q2', 'fuzz_ratio', 'fuzz_partial_ratio',
       'Token_Sort_Ratio', 'Token_Set_Ratio', 'Longest_substr_ratio',
       'last_word', 'first_word', 'length_diff', 'cwc_min', 'cwc_max',
       'csc_min', 'csc_max', 'ctc_min', 'ctc_max', 'mean_length'],
      dtype='object')

In [97]:
### Store data into csv...

df4.to_csv(r'F:\Learn_ai_ml_da\Quora\6.NLP/final_features.csv',index=False)

### Store data into databases

In [121]:
import sqlite3

In [123]:
##Next, create the database. Here, I chose to create a database that is called: ‘TestDB1.db‘

conn = sqlite3.connect('F:\Machine Learning\Projects\Quora/TestDB1.db')
c = conn.cursor()

In [131]:

df4.columns

Index(['0_x', '1_x', '2_x', '3_x', '4_x', '5_x', '6_x', '7_x', '8_x', '9_x',
       ...
       'First_Word', 'Length_diff', 'cwc_min', 'cwc_max', 'csc_min', 'csc_max',
       'ctc_min', 'ctc_max', 'mean_length', 'Longest_Substr_ratio'],
      dtype='object', length=220)


In [ ]:
from sqlalchemy import create_engine
#create sqlalchemy engine by using create_engine method
''' Format of connection string is:
for other databases,we have diff diff formats,for oracle,postgresql
    
    
mysql+pymysql:it is fix    
password is blank
mysql+pymysql://username:password@host:port/database_name'''
create_engine('mysql+pymysql://root:@localhost:3306/Quora')
df.to_sql(
    name='customers', # database table name
    con=engine,
    if_exists='append',
    index=False
)

In [135]:
df4.columns

Index(['0_x', '1_x', '2_x', '3_x', '4_x', '5_x', '6_x', '7_x', '8_x', '9_x',
       ...
       'First_Word', 'Length_diff', 'cwc_min', 'cwc_max', 'csc_min', 'csc_max',
       'ctc_min', 'ctc_max', 'mean_length', 'Longest_Substr_ratio'],
      dtype='object', length=220)