In [1]:
### we need four features as userId , movieId , rating & title to build KNN_based_collabarative_filtering



## ['userId', 'movieId', 'rating']  in  rating.csv
## ['movieId','title']  in   movie.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
### takes 20/30 sec..
###  we will use_cols parameter to load some specific features so that data will get load faster..

data = pd.read_csv(r"F:\Data_science_projects\Recommendation_sytem\Movielens\datasets/clean_data.csv")


In [4]:
data.head(2)

userId  movieId  rating           title                      genres  \
0       1        2     3.5  Jumanji (1995)  Adventure|Children|Fantasy   
1       5        2     3.0  Jumanji (1995)  Adventure|Children|Fantasy   

   TotalRatingCount  
0               112  
1               112

In [5]:
s = set(data['title'])
len(s)

8225

In [6]:
## takes 1 min...

# Create a Pivot Table


##for user 1,we want to check for all movies all movies,ie ,
#(index=title of movies & columns=users)

pivot_table = data.pivot_table(index='title', columns='userId',\
                               values='rating').fillna(0)


In [7]:
pivot_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [8]:
pivot_table.shape

(8225, 702)

In [9]:
#its shape will be (unique Title * unique User ID)

In [10]:
# Convert the pivot_table into an array matrix

from scipy.sparse import csr_matrix
features_matrix = csr_matrix(pivot_table.values)    
# All info of pivot table converted into an array

features_matrix

<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.neighbors import NearestNeighbors   
# it is Not KNearestNeighbors, NearestNeighbors => Unsupervised Algo

model = NearestNeighbors(metric = "cosine", algorithm="brute")
model.fit(features_matrix)    # p=2 => Euclidean Distance Parameter

NearestNeighbors(algorithm='brute', metric='cosine')

In [12]:
#picking up one random record/row
query_index = np.random.choice(pivot_table.shape[0])
query_index

1309

In [13]:
#picking up one random column
query_ind=np.random.choice(pivot_table.shape[1])
query_ind

33

In [14]:
#to check similar movie for 7480 where 7480 is a movie_ID
#values.reshape(1, -1),to get in the form of series

distances, indices = model.kneighbors\
(pivot_table.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 8)

#knn returns distance value ie how far a movie is situated from this movie and their indices also

In [15]:
pivot_table.index[query_index]

'Career Girls (1997)'

In [16]:
distances

### ie 'Tower Heist (2011)' is situated at a distance of 0.03847605 with respect to 'Born American (1986)'..


array([[0.        , 0.21913119, 0.33041052, 0.37530495, 0.39736947,
        0.44784237, 0.44784237, 0.44784237]])

In [17]:
indices.flatten()

array([1309, 1820, 4659, 3415, 7746, 6756, 5121, 4626], dtype=int64)

In [18]:
pivot_table.index[1059]

'Born American (1986)'

In [19]:
pivot_table.iloc[indices.flatten()].index


Index(['Career Girls (1997)', 'Dancemaker (1998)',
       'Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo) (1997)',
       'Hollow Reed (1996)', 'Vanya on 42nd Street (1994)',
       'Some Mother's Son (1996)', 'My Son the Fanatic (1997)',
       'Man of No Importance, A (1994)'],
      dtype='object', name='title')

In [20]:
pivot_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [21]:
pivot_table.index[query_index]

## e.g ,  pivot_table.index[7480]

'Career Girls (1997)'

In [22]:
### so below are the most recommended movies for'Who Framed Roger Rabbit? (1988)'

pivot_table.iloc[indices.flatten()].index

Index(['Career Girls (1997)', 'Dancemaker (1998)',
       'Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo) (1997)',
       'Hollow Reed (1996)', 'Vanya on 42nd Street (1994)',
       'Some Mother's Son (1996)', 'My Son the Fanatic (1997)',
       'Man of No Importance, A (1994)'],
      dtype='object', name='title')

#### lets try to make results more user-friendly...

In [23]:
indices.flatten()

array([1309, 1820, 4659, 3415, 7746, 6756, 5121, 4626], dtype=int64)

In [24]:
distances.flatten()

array([0.        , 0.21913119, 0.33041052, 0.37530495, 0.39736947,
       0.44784237, 0.44784237, 0.44784237])

In [25]:
for i in range(0,len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(pivot_table.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.\
      format(i, pivot_table.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Career Girls (1997):

1: Dancemaker (1998), with distance of 0.2191311905569696:
2: Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo) (1997), with distance of 0.33041051999302484:
3: Hollow Reed (1996), with distance of 0.3753049524455757:
4: Vanya on 42nd Street (1994), with distance of 0.3973694679937223:
5: Some Mother's Son (1996), with distance of 0.4478423696257673:
6: My Son the Fanatic (1997), with distance of 0.4478423696257673:
7: Man of No Importance, A (1994), with distance of 0.4478423696257673:
